### ISSUE TITLE
Count Allies/Enemies in range takes too much time

### ISSUE THREAD

**Issue by L33T** [LeagueSharp/LeagueSharp.CommonEx#3]
Average tick count is around 650 while using CountAlliesInRange or CountEnemiesInRange.
- Distance measurement takes: 6 ticks (~average)
- Distance measurement for 4 other members would take around (6*4 = 24)
- We are losing around 626~ ticks per measurement.

Solution: Add cached enemies/allies and loop through that list, check if they are Valid & Visible, should decrease greatly the tick requirements and increase performance.

**Comment by ChewyMoon** [comment]
Once jodus adds cache next update I think the speed would increase :S

**Comment by L33T** [comment]
Will be added in 5.4 :+1:

**Comment by L33T** [comment]
Will be reworked.

**Comment by ghost** [comment]
Don't think a vision check is a good idea, maybe time since last seen would be a better thing.
