### ISSUE TITLE
Somewhere along the way, Core/Enumerations/CollisionableObjects.cs was lost (blame .gitignore)

### ISSUE THREAD

**Issue by clavin** [LeagueSharp/LeagueSharp.CommonEx#9]
What I mean by that is, regardless of [being added forever ago](https://github.com/LeagueSharp/LeagueSharp.CommonEx/commit/1b0e3be6eb6ae738d14e71d3d883e9d16cee52ec#diff-1e24e437f200ef3361c0ded7325bea3dR72), there never was a file associated with it (not like I looked that much, but I'ma assume).

Thankfully, it's just an enum. I'd submit this as a pull request, but..

![](http://media.catmoji.com/post/w9i/so-lazycant-move-pusheen-the-cat.gif)

Edit:
I FOUND THE ISSUE.

In .gitignore: `*obj*` (it's in the first set of ignore stuff from eclipse)

**Comment by Everesty** [comment]
I FOUND THE ISSUE.

In .gitignore: "*obj*" (it's in the first set of ignore stuff from eclipse)

**Comment by L33T** [comment]
Done, thanks for the report.
